- name : Configure Docker on EC2 Instances
  hosts : webservers
  become: true
  connection : ssh
  tasks : 
  - name: updating apt
    command :  apt update -b

  - name : Install Docker
    command :  apt install -y docker.io 

  - name : Start Docker Service
    command : sudo systemctl start docker

  - name: Deploy Docker Container
    command: docker run -itd -p 8081:8081 ankeetchauhan505/bankingfin
